export const SET_CURRENT_TOP = 'SET_CURRENT_TOP'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_CURRENT_PLAY_SONG_INDEX = 'SET_CURRENT_PLAY_SONG_INDEX'

export const SET_CURRENT_PLAY_SONG = 'SET_CURRENT_PLAY_SONG'

export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS'

export const SET_CATEGORY_GROUP_ID = 'SET_CATEGORY_GROUP_ID'

export const SET_CURRENT_SINGER = 'SET_CURRENT_SINGER'

export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'

export const SET_SEARCH_KEY = 'SET_SEARCH_KEY'

export const SET_SHOW_TOP_BOX = 'SET_SHOW_TOP_BOX'
